### ISSUE TITLE
Debug Output

### ISSUE THREAD

**Issue by boldtrn** [doctrine/DoctrineFixturesBundle#100]
I am wondering if it's possible to have any Debug Output for the Fixtures Creation. I have pretty huge Fixtures, that will need to load pretty long, so it would be really Comfortable to see any Progress.

Is it possible?

**Comment by Invis1ble** [comment]
:+1:

**Comment by alcaeus** [comment]
From a bundle perspective, the only debug output we'd be able to provide is "Loading fixture <xyz>...done" for all fixtures being loaded. We could definitely add that by overriding the default executor, I'm just not sure if it's worth it.

Now that fixtures are services, you can also just inject the logger into your fixtures and log messages with the appropriate severities as you see fit.
