### ISSUE TITLE
Subsequent fixtures drops embedded documents 

### ISSUE THREAD

**Issue by KingCrunch** [doctrine/DoctrineFixturesBundle#101]
I have a curious issue with fixtures and MongoDB. I don't even know, if this is the right place (actually I use https://github.com/hautelook/AliceBundle and didn't try it directly), I just _assume_ that it may caused by this bundle.

I have a document with a list of embedded documents. As long as I run the corresponding fixtures on its own, or as the _last_ fixture everything works fine, but as soon as another fixtures is executed it drops the embedded documents, but nothing else. This means, that the parent document remains, but the property and its values disappear from the database.

Worth to note, that the parent-document is also an extended one (via single-table-inheritance). However, I tried it and every other field, that is unique to the child-document doesn't disappear. Only the embedded documents.

**Comment by lavoiesl** [comment]
Could you provide tests or an example of that?

**Comment by KingCrunch** [comment]
@lavoiesl Now two years later I don't have a project on MongoDB anymore. This said: Sorry, no.
