### ISSUE TITLE
Sharing an ArrayObject or an array between ordered fixtures

### ISSUE THREAD

**Issue by Abam** [doctrine/DoctrineFixturesBundle#103]
I am wondering why it is impossible to share classes (except Entities) between fixtures when using the `addReference` method of `AbstractFixture` class.

I am using in a fixture a code like this :

    //$themes is an array of Entity
    $this->addReference("themes",new \ArrayObject($themes));  

and when I execute the doctrine:fixtures:load command, I am always getting an

    [Doctrine\Common\Persistence\Mapping\MappingException] The class 'ArrayObject' was not found in the chain configured namespaces

**Comment by razmo** [comment]
I have the same problem. Have you found a solution ?

**Comment by lavoiesl** [comment]
No, you have to use a container / dependency injection.
