### ISSUE TITLE
Loading References breaks on STI Root

### ISSUE THREAD

**Issue by rdohms** [doctrine/DoctrineFixturesBundle#108]
Setup:

EntityA is a root class for a STI setup. In its DiscriminatorMap is has `a` pointing to itself and `b` pointing to EntityB. So EntityA is the root but is also a valid entity.

In my Testing setup the ProxyReferenceRepository is used, and it works just fine on the first run, however on the second run (caches not cleared) it breaks with `spl_object_hash() expects parameter 1 to be object, null given`.

I seem to have tracked it to the fact that a null reference is obtained from the unserialization and then once its passed to the setReference() method it breaks the unitofwork since it just calls spl_object_hash on whatever it gets for `isInIdentityMap`.

Any ideas on what is wrong here?

**Comment by lavoiesl** [comment]
Would that be related to https://github.com/doctrine/data-fixtures/pull/170 ? Could you provide tests or a Gist of an example?

**Comment by alcaeus** [comment]
Closing due to lack of feedback.
