### ISSUE TITLE
Add option to set purger.

### ISSUE THREAD

**Issue by bradleytrager** [doctrine/DoctrineFixturesBundle#116]
Right now the ORMPurger is hard coded.  It would be useful if there was an option in the LoadDataFixturesCommand to set which purger to use.

**Comment by vdanielpop** [comment]
Any updates on this one?

**Comment by SenseException** [comment]
No updates afaik. You're welcome if you like to create a PR for this issue.

**Comment by andythedandy** [comment]
Seems to be fixed. Can this be closed now!?

**Comment by SenseException** [comment]
Yes. Thank you for pointing that out.
