### ISSUE TITLE
tries to purge readonly entities

### ISSUE THREAD

**Issue by aur1mas** [doctrine/DoctrineFixturesBundle#118]
I have serveral _DoctrineORM_ entities in `readOnly=true` mode. When I'm running `doctrine:fixtures:load` - it tries to delete them.

I think it shouldn't delete/truncate tables which entities ar marked as readonly?

In my case those entities ar mysql views ...

**Comment by lavoiesl** [comment]
Shouldn’t this be moved to https://github.com/doctrine/data-fixtures ?
