### ISSUE TITLE
Remove exception when no fixtures are found (or add an option to suppress this error)

### ISSUE THREAD

**Issue by benglass** [doctrine/DoctrineFixturesBundle#119]
Currently the command throws an exception if there are no exceptions to load. The issue we are having with this is that it causes problems in automated deployment code when we want to always run fixtures. It returns an error status code when there are no fixtures to run.

Having an option to suppress this exception so it doesnt generate an error status code on the command line (and thus potentially halt the calling scripts) would work fine as well and not introduce a potential BC change. I can submit a PR if this solution would be accepted. Option would be called something like

--allow-empty
--suppress-no-fixtures-exception

**Comment by alcaeus** [comment]
Not sure what you mean with "if there are no fixtures to load" (I assumed you meant fixtures, not exceptions): if you run the load command, we assume you have written fixtures to load - the files to load shouldn't depend on whether data is present in the database.

If you feel this is still an issue, please reopen this ticket with a description of what you're doing.
