### ISSUE TITLE
Possibility To Load Without Purging And Without Duplicates

### ISSUE THREAD

**Issue by sprankhub** [doctrine/DoctrineFixturesBundle#121]
My question is based on [this StackOverflow question](https://stackoverflow.com/questions/22187425/is-it-possible-to-load-doctrine-fixtures-without-deleting-database/22187468).

I am not quite sure if that is the right repository for this question, but you will probably tell me if it is not :-)

Currently, it is afaik not possible to load fixtures without purging the database and without having duplicates. Possibilities:
- `php app/console doctrine:fixtures:load` &rarr; will purge the database
- `php app/console doctrine:fixtures:load --apend` &rarr; will load all fixtures again, so that we may have duplicate entries (for all fixtures which have already been loaded)
- `php app/console doctrine:fixtures:load --apend --fixtures sth` &rarr; that does indeed solve the problem manually. But in this case, I have to know exactly which fixtures have already been loaded and which ones I still have to load. That is not really a feasible solution.

Hence, if I am right, there is no suitable solution for the problem. But I think there definitely should be one...

**Comment by Nemo64** [comment]
Here is an idea for an easy workaround for now:
```PHP
public function load(ObjectManager $manager)
{
    $achievement = $this->createAchievement($id);
    // set here everything
    $manager->persist($achievement);
    $manager->flush();
}

public function createAchievement($id, ObjectManager $manager)
{
    return $manager->find('Achievement', $id) ?: new Achievement($id);
}
```

**Comment by J7mbo** [comment]
It would be great to have the option to `--skip-duplicates` or similar for those of use who want to be able to load fixtures but not overwrite other parts of the database.

**Comment by lavoiesl** [comment]
This would be incredibly complicated to do in a general way. I suggest you simply write helpers to do that. Personally, I do this:

```php
<?php
public function load(ObjectManager $manager)
{
    $obj = $manager->getRepository('Acme:Entity')->findById(123);
    if (!$obj) {
        $obj = new Entity;
        $obj->setId(123);
        $manager->persist($obj);
    }
    $obj->setName('foo');
    $manager->flush();
}
?>
```

**Comment by NV-iloweb** [comment]
+1 for this request
Would be nice to have this functionnality.

**Comment by kaiwa** [comment]
@KingCrunch commented on 8 Jul 2014
> I assume I know, what you are trying to do: Fixtures <b>are not intended to be used in production</b> 
> environments. You should use migrations for that.

The sf docs are misleading if fixtures are really not intended for prod initialization:

http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html

> This data can be used for testing <b>or could be the initial data required for the application
> to run smoothly</b>

**Comment by xDaizu** [comment]
I agree with @lavoiesl that it would be very difficult. I'd say nigh impossible, not at a technical level but at design level, because how would you know if an entry is duplicate or not? You could guess if a field is "unique" but then what? What if the rest of fields are different? Do you update them or do you keep the original? 

The business logic of the requisite is so fine-grained that it would require a very verbose syntal, so... you'd be better off implementing it yourself in the fixture function. I mean, it's plain php, you can check stuff before adding :)

**Comment by ziegfridhn** [comment]
In Laravel Seeder you can just specify the class which to run and avoid this all together

**Comment by msalsas** [comment]
I just want to share a simplified piece of code to check if entity already exists in DB.

Replace `'unique_field'`, `$uniqueProperty` and `setUniqueProperty` with your custom unique property name (the one that better defines your entity)

```
<?php
public function load(ObjectManager $manager)
{
    $uniqueProperty = "foo"; // Your logic to assign static or dynamic unique property
    if ($manager->getRepository(YourEntity::class)->findOneBy(['unique_field' => $uniqueProperty])) {
        return;
    }

    $entity = new YourEntity();
    $entity->setUniqueProperty($uniqueProperty);
    $manager->persist($entity);
    $manager->flush();
}
?>
```
