### ISSUE TITLE
PostgreSQL failing to locate tables because schema is missing?

### ISSUE THREAD

**Issue by matt-usurp** [doctrine/DoctrineFixturesBundle#124]
I am aware that this project is a wrapper for the data fixtures project, so I will make an issue there should this actually turn out to be a bug. But there is not documentation on where to make issues for this project so here one is.

---

I am having this tennis match with Doctrine and its Fixture manager bundle. Tweaking configuration will break one or the other, there doesn't appear to be a middle ground where we all play nice. I believe the issue lies within the fixtures code as the tweak to make it work is considered a "work around" on the internet and the ORM (which i consider more reliable and stable) works fine without it.

So executing the following:

``` sh
$ bin/console doctrine:schema:update --force
Nothing to update - your database is already in sync with the current entity metadata.

$ bin/console doctrine:fixtures:load
[Doctrine\\DBAL\\Exception] TRUNCATE story CASCADE;
```

My issue lies with the truncate statement not containing the schema. My configuration is setup so that the username is not matching the schema, instead the dbname is considered the schema (according to documentation and what I have seen in the ORM). Adding the schema to column's name attribute in the annotation does fix this but will then break the ORM. The ORM will constantly complain that the database is out of date.

There seems to be limited documentation on the PostgreSQL but I am guessing that the expected statement would will contain the schema name `TRUNCATE champion.story CASCADE;`.

---

My configuration for doctrine is as follows:

``` yaml
doctrine:
  dbal:
      driver: pdo_pgsql
      host: 127.0.0.1
      dbname: champion
      user: postgres
      password: password
```

Here is the basics of my Entity

``` php
/**
 * Bare in mind the "name" works with "champion.story" but breaks ORM.
 * @ORM/Column(name="story")
 */
class Story {}
```

**Comment by lavoiesl** [comment]
Are you are looking for https://github.com/doctrine/data-fixtures/pull/171 ? It will be released next week.

Otherwise, you class annotation is wrong, you need `@ORM\Table(name="story")`. Also, you can override the schema with: `@ORM\Table(name="story", schema="champion")`

**Comment by matt-usurp** [comment]
I don't think this is an issue anymore so closing.
