### ISSUE TITLE
Fatal error: Class 'AppBundle\AppBundle' not found in \app\ AppKernel.php 

### ISSUE THREAD

**Issue by sruj** [doctrine/DoctrineFixturesBundle#132]
Im trying to install and use DoctrineFixturesBundle but result in a problem.

I install bundle following the instruction http://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html

and after all when i try to use cosole in the project i got this message:

C:\wamp\www\17bezboga>php app/console generate:bundle

Fatal error: Class 'AppBundle\AppBundle' not found in C:\wamp\www\17bezboga\app\
AppKernel.php on line 19

Call Stack:
    0.0000     125624   1. {main}() C:\wamp\www\17bezboga\app\console:0
    0.2031    2293504   2. Symfony\Component\Console\Application->run() C:\wamp\
www\17bezboga\app\console:27
    0.2500    2446120   3. Symfony\Bundle\FrameworkBundle\Console\Application->d
oRun() C:\wamp\www\17bezboga\vendor\symfony\symfony\src\Symfony\Component\Consol
e\Application.php:126
    0.2500    2446232   4. Symfony\Component\HttpKernel\Kernel->boot() C:\wamp\w
ww\17bezboga\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\A
pplication.php:70
    0.2500    2446376   5. Symfony\Component\HttpKernel\Kernel->initializeBundle
s() C:\wamp\www\17bezboga\app\bootstrap.php.cache:2330
    0.2500    2446616   6. AppKernel->registerBundles() C:\wamp\www\17bezboga\ap
p\bootstrap.php.cache:2500

C:\wamp\www\17bezboga>

detailed description here:
 http://stackoverflow.com/questions/27768727/cant-run-symfony2-after-installing-new-bundle-with-composer

**Comment by stof** [comment]
Your issue does not come from a DoctrineFixturesBundle file at all, but from your own kernel, where the ``AppBundle\AppBundle`` class cannot be autoloaded.
