### ISSUE TITLE
Doctrine Fixture vendor library not loading after composer update

### ISSUE THREAD

**Issue by sakoh** [doctrine/DoctrineFixturesBundle#133]
I added 
```javascript
{
    "require": {
        "doctrine/doctrine-fixtures-bundle": "2.2.*"
    }
}
````

to composer.json and ran `composer update` and it doesn't load the doctrine fixtures library in the vendor directory. Can anyone help me out?

**Comment by lavoiesl** [comment]
This seems very unlikely. Try removing your vendor directory and providing the output of `composer update -vvv`

**Comment by stof** [comment]
Closing as no feedback has been given
