### ISSUE TITLE
This bundle still alive?

### ISSUE THREAD

**Issue by hoshsadiq** [doctrine/DoctrineFixturesBundle#135]
Nothing seems to get merged and I want to make some improvements, but if it's just not gonna get merged, I'm not gonna bother and instead will put it in my own repository.

**Comment by lavoiesl** [comment]
There are 2 new contributors, including me, that are working on the library and this bundle. I am currently focusing on the library, but I will look at the bundle afterwards. You are welcomed to send PRs.
