### ISSUE TITLE
GeneratedValue + UUID

### ISSUE THREAD

**Issue by bassrock** [doctrine/DoctrineFixturesBundle#136]
Hi Am using the following for all my ids on my entities:

```
    /**
     * @var string
     *
     * @ORM\Column(name="id", type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;
```

This fails in a lot of my data fixtures, because the id of an object is not yet set, since it uses the UUID function in MySql.

Is there a way to persist entities instead of waiting till the end?

**Comment by bassrock** [comment]
Also note, that it worked fine when I was using Auto Incremented values.

**Comment by bassrock** [comment]
nvm

**Comment by hallabro** [comment]
@bassrock could you please describe what you did differently to get it to work?

**Comment by bassrock** [comment]
@hallabro nothing, it just started working. Its possible it was a mysql version issue.
