### ISSUE TITLE
What is v2.21?

### ISSUE THREAD

**Issue by zerkms** [doctrine/DoctrineFixturesBundle#144]
At https://packagist.org/packages/doctrine/doctrine-fixtures-bundle

**Comment by stof** [comment]
a mistake when creating the tag, and I spotted it only when pushing. The same commit is tagged as v2.2.1 and the v2.21 tag has been deleted.

@beberlei can you delete this version from Packagist ? you are the only package maintainer there so you are the only one able to do it.

**Comment by beberlei** [comment]
@stof done, thanks for pinging me, i only rarely check notifications nowadays.

**Comment by stof** [comment]
@beberlei maybe other maintainers of each Doctrine package should be added as packagist maintainers. What do you think ?
