### ISSUE TITLE
fixtures:load should write on which query was error

### ISSUE THREAD

**Issue by poolerMF** [doctrine/DoctrineFixturesBundle#153]
hello

I'm making some fixtures .. and in one fixture I have more than 20 queries (selects, updates ...)

when load fixture fails, I only see errors like:

```
[Symfony\Component\Debug\Exception\ContextErrorException]
Warning: spl_object_hash() expects parameter 1 to be object, null given


[Symfony\Component\Debug\Exception\FatalErrorException]
Error: Call to a member function add() on a non-object
```

(FatalErrorException is my error, I know ... but ..)
but I'm doing query more times .. and I don't know which entity fails or which query fails

can you make better log of exception ? (which entity/query/line ?)

thank you

**Comment by alcaeus** [comment]
I'm not sure the errors you mentioned are even related to SQL execution. If you can write a test that reproduces them, feel free to reopen this.
