### ISSUE TITLE
Use ContainerAwareTrait instead of own implementation

### ISSUE THREAD

**Issue by JHGitty** [doctrine/DoctrineFixturesBundle#154]
The new ``ContainerAwareTrait`` should be used instead of an own implementation.

Example:
https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#using-the-container-in-the-fixtures

This:
```php
class LoadUserData implements FixtureInterface, ContainerAwareInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }
```

Should be changed to:
```php
class LoadUserData implements FixtureInterface, ContainerAwareInterface
{
  use ContainerAwareTrait;
```

**Comment by peterrehm** [comment]
@JHGitty Can you create a PR for that?

**Comment by steevanb** [comment]
You can't do that, cause traits are available since PHP 5.4, and only 5.3.2 is required via composer.json.

**Comment by stof** [comment]
there is nothing wrong about using an explicit implementation

**Comment by JHGitty** [comment]
Closed. Reason: see @steevanb
