### ISSUE TITLE
Why doesn't doctrine fixture bundle truncate symfony ACL tables?

### ISSUE THREAD

**Issue by Redigast13** [doctrine/DoctrineFixturesBundle#158]
I use symfony symfony/security-acl bundle with doctrine fixtures bundle. I created acl tables using php bin/console init:acl command, also I could created them using php bin/console doctrine:schema:update --force command.

I load fixtures using php bin/console doctrine:fixtures:load command. If I use this command it truncates all tables except the acl_\* tables (acl_classes, acl_entries, acl_object_identities, acl_object_identity_ancestors, acl_security_identities) before executing. Why does it happen and how to make this command to truncate all DB tables?

**Comment by gregurco** [comment]
symfony/security-acl works with doctrine, but doesn't use ORM. It simply generates tables by raw sql and work with data from tables by executing raw sql too. You can see it here: https://github.com/symfony/security-acl/blob/master/Dbal/MutableAclProvider.php#L386

But ORMPurger, which purges the DB, work with ORM and tries to find list of tables by list of known entities.
As a solution you can create entities for acl_* tables, or write yml schema, or somehow add DatabaseDriver to EntityManager (by default there is AnnotationDriver only).
