### ISSUE TITLE
DoctrineFixturesBundle doesn't work right when used  in a nested entity

### ISSUE THREAD

**Issue by videni** [doctrine/DoctrineFixturesBundle#171]
Since  the version of DoctrineFixturesBundle  is greater than  v2.21  , It will give this error when a class is an nested entity

> Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its dependency. Then, class B has class A has  
>    its dependency. Finally, class A has class C as its dependency.

**Comment by 9orky** [comment]
Same here. I did an update yesterday and experience the same exception. What's even more I've tested it against an empty test - result is the same.

**Comment by videni** [comment]
@9orky ,   right now we can   force  version `doctrine/data-fixtures` as  "1.1.1",     `doctrine/data-fixtures                           v1.2.0`     introduced  a  TopologicalSorter  class, this class throw this error

**Comment by alcaeus** [comment]
Cyclic dependencies can't be solved here: A needs to be run for B to have its dependencies fulfilled, which in turn is required for C. However, when A needs C to run, there's no solution to the problem, hence the exception. The only solution is to properly refactor your fixtures to not have cyclic dependencies.
