### ISSUE TITLE
Probleme avec les relation "ManyToMany" & "ManyToOne"

### ISSUE THREAD

**Issue by Doufani** [doctrine/DoctrineFixturesBundle#172]
I created my entity
I defined the relationship ManyToMany & ManyToOne
when I wonna fill the relationship field  

$ Annonce2-> setAnnonceur ($ this-> getReference ( 'annonceur2'));

i got this error :
catchable fatal error argument 1 passed to must be an instance of

**Comment by gregurco** [comment]
@Doufani do you have somewhere `$this->addReference('annonceur2', $variable);` ?

**Comment by alcaeus** [comment]
Closing due to no feedback - @Doufani please reopen if this is still relevant.
