### ISSUE TITLE
Input option "multiple-transactions" sets not existing method argument in ORMExecutor

### ISSUE THREAD

**Issue by davidgorges** [doctrine/DoctrineFixturesBundle#173]
The latest version of `LoadDataFixturesDoctrineCommand` adds an option "multiple-transactions" which gets passed into [ORMExecutor's execute()](https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php#L80) as a third argument (introduced in #113). However, the current release (and version specified in composer.json) of doctrine/data-fixtures does not support such a third argument.

However, there is an open [pull request](https://github.com/doctrine/data-fixtures/pull/209) that tries to add this functionality.

**Comment by romaricdrigon** [comment]
We just fell on the same issue.
Having something documented in the Symfony command but not supported by the library is extremely disappointing, and the user has no feedback.

Could the option be removed or an Exception be thrown to indicate that the option is not (yet) supported in the library? What do you think @stof  - it looks like a major pitfall regarding DX.

**Comment by fabpot** [comment]
Reverted
