### ISSUE TITLE
load task not using Entity table name

### ISSUE THREAD

**Issue by Sgoettschkes** [doctrine/DoctrineFixturesBundle#18]
I got a entity named "order" within my application and cannot use doctrine:fixtures:load as it tries to DELETE FROM order which breaks MySQL. I got the following annotation within the entity, but it doesn't change anything:
`@ORM\Table(name="`Order`")`

As a quickfix, I added line 119 in Doctrine\Common\DataFixtures\Purger\ORMPurger:
`$tbl = '`' . $tbl . '`';`

It works for me now, but I guess that's not a clean solution.

**Comment by titenis** [comment]
I am still able to replicate this, though. The entity is named 'Order' and purging of database is not working.
