### ISSUE TITLE
Why do the documentation suggest to place fixtures in the source directory?

### ISSUE THREAD

**Issue by Kwadz** [doctrine/DoctrineFixturesBundle#186]
Why does the [documentation](http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#writing-simple-fixtures) suggest to place fixture files in the `src/` directory while it's a [good practice](https://symfony.com/doc/current/bundles/best_practices.html#directory-structure) to place everything related to the tests in `tests/` or `<your-bundle>/Tests/` directories?

**Comment by Kwadz** [comment]
I just realize fixtures can also be used out of testing scope, for example to make the application work if it needs initial data.

**Comment by eerison** [comment]
I came with the same question.

But it's not necessary for prod code, why do we need load this?

maybe it should be in `<your-bundle>/Fixtures/` ? like others https://github.com/theofidry/AliceBundle does?
