### ISSUE TITLE
[DX] Using Doctrine\Bundle\FixturesBundle\EmptyFixture is bad

### ISSUE THREAD

**Issue by Zzortell** [doctrine/DoctrineFixturesBundle#206]
Hello!

After this strange line appears in my console:
```
  > loading Doctrine\Bundle\FixturesBundle\EmptyFixture
```
I came here and read this conversation: https://github.com/doctrine/data-fixtures/pull/252

I think that if this pull-request had been accepted, it would have been great as `Doctrine\Bundle\FixturesBundle\Fixture` could implement `Doctrine\Common\DataFixtures\DependentFixtureInterface` whatever the fixture has dependencies or not.

However, the Doctrine team has ruled that no-dependency fixtures should not implement `DependentFixtureInterface`, so this bundle should not try to bypass that decision by loading an useless fixture. It can be confusing for the developer (especially if he thinks one of his dependency transformed into `EmptyFixture` ^^). It simply makes no sense to load an `EmptyFixture` if one of your fixture has no dependency. No-dependency fixtures should not implement `DependentFixtureInterface`, unless Doctrine enable `getDependencies()` returning empty array.

Moreover, the role of a Symfony bundle is to add ContainerAware ability to bridge the Doctrine data fixture library and Symfony services, not to enforce the user implementing  `DependentFixtureInterface`. It should be up to the user implementing it or not.

So I think we should remove dependency management from this bundle as well as EmptyFixture.

**Comment by weaverryan** [comment]
Yea... it's tough, because we strongly disagree with the decision by the Doctrine team in this situation. So, at some point, we need to work around their decisions to add better DX.

But, I also don't like the output - it confused me too. I'm going to add a PR to actually hide it - #210

**Comment by alcaeus** [comment]
Fixed by #209 which solves the issue by not implementing `DependentFixtureInterface` by default. Closing here.
