### ISSUE TITLE
Sensio Insight Issue - Doctrine Entity Manager should not be passed as argument

### ISSUE THREAD

**Issue by ravindrakhokharia** [doctrine/DoctrineFixturesBundle#218]
In one of our project, we do use Sensio Insights scanning, which flagged the above issue. 

![image](https://user-images.githubusercontent.com/2654612/33418118-5e861c3e-d5ca-11e7-9240-7a4e7b095a01.png)

Our Fixture files implements AbstractFixture interface to create a new fixture, which further has below hierarchy of fixtures used as below. 

![image](https://user-images.githubusercontent.com/2654612/33418197-bf3205b6-d5ca-11e7-98db-7de3ec94fa2b.png)

AbstractFixture > SharedFixtured >> FixtureInterface has method "load" which needs ObjectManager as argument, due to which we get above flagged in sensio insights ! 

Any suggestions for above issue?

Thanks in advance.

**Comment by alcaeus** [comment]
This is an issue with Sensio Insights - you should report it to them. Passing the entity manager is perfectly fine in this case. Closing as `Wontfix`.

**Comment by ravindrakhokharia** [comment]
@alcaeus Thanks for your comment, We will escalate this with Sensiolabs. 

thanks!

**Comment by RenierLewis** [comment]
I have raised a support issue with Sensiolabs 
https://support.sensiolabs.com/hc/requests/7117

Thanks
Renier

**Comment by RenierLewis** [comment]
From Sensiolabs:

Julien Beaulieu (SensioLabs Support) Dec 7, 11:30 CET Hello,That is indeed a false positive. We are going to work on it, thanks for the feedback.Best regards, | Julien Beaulieu (SensioLabsSupport)Dec 7, 11:30 CET Hello,That is indeed a false positive. We are going to work on it, thanks for the feedback.Best regards,
