### ISSUE TITLE
Avoid requiring FrameworkBundle

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineFixturesBundle#224]
This bundle doesn't need symfony/framework-bundle, but it's currently requiring it.
I thinks such require should be moved to require-dev, and explicit symfony packages should be required instead:
* symfony/config
* symfony/console
* symfony/dependency-injection
* symfony/http-kernel

**Comment by Taluu** [comment]
Removing `symfony/framework-bundle` and using the mentionned bundles is not enough, as this bundle requires `doctrine/doctrine-bundle` which requires the `symfony/framework-bundle` anyway.

But doctrine's bundle is only used for the `DoctrineCommand`, which is useless as no helpers from that command are actually used. So the first step would be to remove the `doctrine/doctrine-bundle` dependency, and work towards removing the `symfony/framework-bundle` after.

**Comment by patie** [comment]
doctrine/DoctrineFixturesBundle for sure dont need full FrameworkBundle which for example require deprecating symfony/templating, so please require only packages which are required, not full FrameworkBundle

**Comment by alcaeus** [comment]
@patie feel free to continue the work started by @Taluu in #234.

**Comment by BenoitDuffez** [comment]
Hi, not really related, but I would like to understand why there are some requirement on symfony packages?

As far as I understand, Doctrine is a PHP/composer library that provides a PHP DB abstraction. Symfony is a framework to make web applications.

My concern is that I'm writing a PHP/composer library that uses a database, and I chose to use Doctrine. Now I don't understand why I have some Symfony packages on this library, which can be used in any composer project (some don't include Symfony).

**Comment by BenoitDuffez** [comment]
I grepped the code of this repo, and I can see it's used by the commands (I/O interfaces and Symfony fixtures loader — this makes sense), tests (HttpKernel, but then it should be in require-dev if it's for tests) and then for DI to automatically hook services and fixtures.

I guess it's too tightly hooked with Symfony to get rid of it from the dependencies.

**Comment by Taluu** [comment]
It's a symfony bundle so...

**Comment by BenoitDuffez** [comment]
Doctrine is not related to Symfony, and DoctrineFixtures doesn't necessarily imply Symfony in my opinion.

But you're right.

**Comment by Taluu** [comment]
I mean this repository is the integration of doctrine data fixtures and symfony so it's normal and expected there should be symfony deps...

You use the data-fixtures if you want, there are no sf dependencies... https://github.com/doctrine/data-fixtures/blob/master/composer.json

**Comment by BenoitDuffez** [comment]
Thanks! I got confused I guess :)

**Comment by alcaeus** [comment]
@BenoitDuffez as already mentioned, this is a library to integrate the fixtures library with Symfony, allowing users to configure their fixtures in the framework configuration file.

If you are building a database library, you should not rely on this bundle but rather on the `doctrine/data-fixtures` package. While that package (and other Doctrine libraries) have dependencies on Symfony code, this is much more localised to satisfy certain use-cases (e.g. using `symfony/console` for our CLI commands, or `symfony/yaml` to parse YAML configuration files).
