### ISSUE TITLE
load fixtures from a specific folder only

### ISSUE THREAD

**Issue by craue** [doctrine/DoctrineFixturesBundle#226]
With 3.0, how is it possible to make the `doctrine:fixtures:load` command consider fixtures from a specific folder only, like the `--fixtures` option did? This feature is [still needed](https://github.com/craue/CraueGeoBundle/pull/16#issuecomment-352023730).

**Comment by alcaeus** [comment]
Duplicate of #219. Closing to consolidate discussion.
