### ISSUE TITLE
--fixtures option no more supported

### ISSUE THREAD

**Issue by DylanGD** [doctrine/DoctrineFixturesBundle#227]
Hi,

Did you remove this option from the package ?
Can't use anymore : 

php bin/console doctrine:fixtures:load **--fixtures**=src/MyBundle/DataFixtures/ORM/MyFixtures.php --append

Current version is : 3.0.2

Thanks

**Comment by alcaeus** [comment]
#219.

**Comment by derekparnell** [comment]
Does anyone have a link as to why this option was removed?  I'm trying to figure out what it gains us as opposed to the detriment of not having it.

**Comment by alcaeus** [comment]
Please move discussion to #219. Thanks.
