### ISSUE TITLE
Can I send the logged user into the fixtures?

### ISSUE THREAD

**Issue by roberto910907** [doctrine/DoctrineFixturesBundle#239]
I want to use Symfony Process Component for calling the fixture load, but I want to send the current user at the moment of execute the action of the controller that launch the process. I know if you inject the token storage as argument of fixture the **getToken** method will be null because is another context. Is there any way to send the user's object into the fixtures? Maybe using the entity manager for saving as reference and use it just like sharing objects `$this->getReference('user_stored');` inside the fixture. Is this possible?

**Comment by alcaeus** [comment]
No, this is not possible. You'd most likely need to override the loader to be able to accept outside arguments. Fixtures are meant to be a set of data used to pre-populate the database for tests or to get basic data into a production system - once. I'm not sure what your use-case is, but I can tell you that it falls outside the scope of this bundle.

**Comment by roberto910907** [comment]
@alcaeus Thank you so much for your answer. What I need to do is initialize the data for some database tables in a visual way. When I create a new account for a company, the first time that a user that belongs to that company log in into the system, the default data should be pre-loaded but I need to `set` the company of that user for every row inserted. I'll try to override the loader or implement the loading process in my own way.
