### ISSUE TITLE
Can we set path for version 3 ?

### ISSUE THREAD

**Issue by bluepioupiou** [doctrine/DoctrineFixturesBundle#242]
Hi all, it seems that at some point of the bundle we had the possibility to call the command with --fixtures option to pass another path.
Is there a way to have this one way or another in version 3.x ?

**Comment by alcaeus** [comment]
See https://github.com/doctrine/DoctrineFixturesBundle/issues/219#issuecomment-352337579. Implementations are highly welcome since the time I can allocate for OSS is severely limited at the moment.
