### ISSUE TITLE
--fixtures option

### ISSUE THREAD

**Issue by eldiablo62** [doctrine/DoctrineFixturesBundle#247]
Hi, 

I use symfony 3.4.8 and i haven't see --fixtures option ?
When i tried to use this option, 

php bin/console doctrine:fixtures:load --fixtures=/path/to/fixtures1
 I have this message : 
 The "--fixtures" option does not exist. 

This option was removed ?

**Comment by strawburrypokki** [comment]
Hi, in the 3.x version the option `--fixture` was removed.  
Sadly, I don't think there any alternative for now.

There is an ongoing discussion about implementing this feature again, here : #219

**Comment by alcaeus** [comment]
Thanks @strawburrypokki! I suggested a solution in a comment (https://github.com/doctrine/DoctrineFixturesBundle/issues/219#issuecomment-352337579) - it's just waiting for someone who needs it badly enough to implement it - I currently have neither the need, nor the time to implement it myself. I'm closing this issue to consolidate discussion in the linked issue.

**Comment by rumours86** [comment]
https://github.com/doctrine/DoctrineFixturesBundle/pull/250
