### ISSUE TITLE
No way to load only chosen fixtures in 3.0?

### ISSUE THREAD

**Issue by Destroy666x** [doctrine/DoctrineFixturesBundle#249]
I came across 2.x in my project and there was no DI, so I wanted to upgrade to 3.0. To my surprise, unless I'm missing something obvious, loading only chosen fixtures, e.g. with Phing, looks impossible. This looks like a big downgrade, you can't have e.g. 3 different sets of fixtures for the same entities that can be switched quickly.

**Comment by weaverryan** [comment]
Hi there!

See #219 - the removal was accidental. We just need someone to create a PR to bring it back - if you’re able to do that and need guidance, if beg appt to help :)

**Comment by Destroy666x** [comment]
Ok, thanks for info.

**Comment by rumours86** [comment]
https://github.com/doctrine/DoctrineFixturesBundle/pull/250
