### ISSUE TITLE
Argument 1 passed to Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader::addFixture() must be an instance of Doctrine\Common\DataFixtures\FixtureInterface

### ISSUE THREAD

**Issue by sterichards** [doctrine/DoctrineFixturesBundle#252]
Full error - Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader::addFixture() must be an instance of Doctrine\Common\DataFixtures\FixtureInterface, instance of Abstrat\OAuthBundle\Controller\TokenController given, called in /var/www/html/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php on line 36 in /var/www/html/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php on line 40

services.yml:

```services:
  abstrat.oauth.token_controller:
    class: Abstrat\OAuthBundle\Controller\TokenController
    arguments: ['@fos_oauth_server.server']
    calls:
      - [setContainer, ["@service_container"]]
    tags: [doctrine.fixture.orm]
```

How do stop TokenController being passed?

**Comment by stof** [comment]
Well, why are you tagging your controller as `doctrine.fixture.orm` ? That tag is the one making it being passed to the fixtures loader.

**Comment by sterichards** [comment]
This is an inherited library that works fine with 2.7

I'm struggling to find any documentation that helps with migrating services.yml from 2.7 to 3.4

**Comment by sterichards** [comment]
Can you understand why "This command looks for all services tagged with doctrine.fixture.orm. If you're using the default service configuration, any class that implements ORMFixtureInterface (for example, those extending from Fixture) will automatically be registered with this tag." wouldn't work for me and i've seen other people on Stack mentioning that it doesn't work for them either

Source of quote - https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html

**Comment by stof** [comment]
The issue you have is that you are manually adding the tag on a service which is **not** a fixture. and so, when looking for services having this tag, it will also find your controller (but trying to use it as a fixtures does not work).

You should not be tagging random services as `doctrine.fixture.orm`. that won't work (that's actually true for almost any tag which is being used for some effect actually)

**Comment by stof** [comment]
in your quote, there is 2 sentences. The second sentence does not apply at all in your case (you don't implement the interface, so the bundle will not automatically add the tag). But the first sentence applies. And it says `all services tagged with doctrine.fixture.orm`. It does not care about whether the tag was added automatically by the autoconfiguration system or explicitly in the service definition (and that's actually one of the strength of the way autoconfiguration works in Symfony)

**Comment by sterichards** [comment]
I've managed to define the DF's and tag them using the following:

```Abstrat\OAuthBundle\DataFixtures\:
    resource: '../.././DataFixtures'
    tags: ['doctrine.fixture.orm']```

This was only worked out because of a random Stack post I found. There is zero documentation that informs me that I need to do this :(

**Comment by stof** [comment]
@sterichards the issue you reported above was not related at all to not having the tag on your actual fixtures. It was caused by you adding the tag on a totally unrelated service.
