### ISSUE TITLE
DoctrineFixturesBundle not added to bundles.php (SF4)

### ISSUE THREAD

**Issue by ajie62** [doctrine/DoctrineFixturesBundle#261]
Hi, I was about to work with fixtures on a SF4 project, so I used flex and ran:

```bash
composer req orm-fixtures
```
Everything worked fine, but then when I tried to use a fixture I made by running 

```bash
bin/console doctrine:fixtures:load
``` 

the following message appeared:

![Screenshot](https://user-images.githubusercontent.com/16993336/48633259-4298ba00-e9c3-11e8-8245-a89f1d3c0ec6.jpeg)

I went to look in config/bundles.php and noticed it had not been added to it. I added it:

```php
<?php

return [
    // ...
    \Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true],
];
```

Then I tried to load the fixtures again and it worked.

Would it be conceivable to make a recipe to instantly add the bundle inside config/bundles.php, or is there another way to do it that I'm not aware of? Anyway, this is my first contribution and I'm just willing to help, so please be understanding.

**Comment by osavchenko** [comment]
Can't reproduce this issue with STR you provide

**Comment by alcaeus** [comment]
I could not reproduce it either, closing here due to that and lack of feedback. Either way, this is nothing we can fix but rather a problem with flex or the recipe (if it's a problem at all).
