### ISSUE TITLE
BC break in 3.0.3

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineFixturesBundle#266]
This [commit](https://github.com/doctrine/DoctrineFixturesBundle/commit/0b0fba559cb4e7fb179e33f149b2324bcb0f0c33) is a BC break.
Until version 3.0.2, using command `console doctrine:fixtures:load` with `-n` option you get the fixtures loaded without confirmation.
In version 3.0.3, it's the opposite: the same option is silently refusing to load fixtures, giving no feedback.

Please restore previous behavior. In the future, it can be added in a major version.

**Comment by sanis** [comment]
Confirm of that.

**Comment by alcaeus** [comment]
3.0.4 has been released. Thanks for reporting this!
