### ISSUE TITLE
Doctrine Fixture Bundle in Vendor

### ISSUE THREAD

**Issue by drbarzaga** [doctrine/DoctrineFixturesBundle#268]
I have a symfony vendor in my private repository which contains some fixtures, how can I execute these from my application once the vendor is installed in it?

**Comment by alcaeus** [comment]
First of all, please use English to help us help you. I don't speak Spanish, so any more complex questions that Google Translate would choke on would get lost in translation ^^.

Here's what I got for your question:

> I have a symfony vendor in my private repository which contains some fixtures, how can I execute these from my application once the vendor is installed in it?

Assuming you're using version 3 of the bundle, you can declare these Fixtures as services and tag them with the `doctrine.fixture.orm`. If you're using auto configuration in your services, they will be tagged automatically, so all you have to do is declare a service for them.

**Comment by drbarzaga** [comment]
@alcaeus 

Perfect thanks for responding carefully, I'm using symfony 3.4 in my application, in my private vendor I have some fixtures but when I try to declare it as a service it does not allow me to put the tag **doctrine.fixtures.orm** ? do you have any idea?

**Comment by alcaeus** [comment]
> it does not allow me to put the tag

You're going to have to be more specific here: without error messages or traces we can't really do anything.

**Comment by drbarzaga** [comment]
@alcaeus 
Well really what I was referring to is that I did not complete the doctrine.fixture.orm tag in PhpStorm but I put it in anyway and it worked for me. Thank you very much for your help.
