### ISSUE TITLE
config custom dir of `Datafixtures`

### ISSUE THREAD

**Issue by lichnow** [doctrine/DoctrineFixturesBundle#276]
can change the dir of Datafixtures now? because,when use api platform，app will has many dir like dto,dataprovider...,I want to move that all to `src/Data` path like `src/Data/Fixtures`. have any configure to DataFixtureBundle?

**Comment by weaverryan** [comment]
In the latest version of this bundle, the bundle doesn't care at all what directory you put your stuff into - it uses the interface/base class that your fixture implements to find it. So, yea, move your classes where ever you want - it'll just work :)

**Comment by J7mbo** [comment]
Hi @weaverryan, I placed my DataFixtures in the very top level directory, so before `src/`.

> root@3a2a2ad4d76c:/app# bin/console doctrine:fixtures:load --append
> loading App\DataFixtures\AppFixtures

However, I don't have an `App\DataFixtures\AppFixtures` - where on earth has that come from? I have my own:

```
namespace DataFixtures;

class DefaultUsersFixtures extends Fixtures implements ORMFixture Interface { /* ... */ }
```

And the fixture isn't loaded. I think this is related to this ticket as I want a dir outside of `src/`, or am I missing something?
