### ISSUE TITLE
Composer deprecation notices

### ISSUE THREAD

**Issue by adrienfr** [doctrine/DoctrineFixturesBundle#304]
Hi,

Since composer 1.10 release ([here](https://github.com/composer/composer/releases/tag/1.10.0)), I have the following deprecation notices:

> Deprecation Notice: Class Doctrine\Bundle\FixturesBundle\Tests\IntegrationTest\IntegrationTest located in ./vendor/doctrine/doctrine-fixtures-bundle/Tests/IntegrationTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
> Deprecation Notice: Class Doctrine\Bundle\FixturesBundle\Tests\IntegrationTest\IntegrationTestKernel located in ./vendor/doctrine/doctrine-fixtures-bundle/Tests/IntegrationTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

Is this something you already fixed somewhere?

Thanks

**Comment by alcaeus** [comment]
Fixed in #306, will be included in 3.3.1.
