### ISSUE TITLE
`EntityManager` injected instead of type-hinted `ObjectManager`

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/DoctrineFixturesBundle#323]
I'm getting this error from [phpstan](https://github.com/phpstan/phpstan):

> Parameter #1 $manager (Doctrine\Persistence\ObjectManager) of method App\DataFixtures\TestFixtures::load() is not compatible with parameter #1 $manager (Doctrine\Persistence\ObjectManager) of method Doctrine\Common\DataFixtures\FixtureInterface::load().

Following https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html this is what I have in the file:
```php
namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;

class TestFixtures extends Fixture
{
    public function load(ObjectManager $manager)
    {
        print_r(get_class($manager));
        die;
    }
}
```
And indeed, the output I'm getting is:
> Doctrine\ORM\EntityManager

So `EntityManager` gets injected, whereas `load()` expects `ObjectManager`

**Comment by xabbuh** [comment]
The `EntityManager` class implements the  `EntityManagerInterface` which extends the interface `ObjectManager`. I don't see why that should be an issue here.

**Comment by ThomasLandauer** [comment]
@greg0ire cool - thanks - that fixed it for me!

Should I make a PR and change `use Doctrine\Common\Persistence\ObjectManager;` right away at https://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#writing-fixtures ?

**Comment by greg0ire** [comment]
Yes please!

**Comment by ThomasLandauer** [comment]
There you go :-)
https://github.com/doctrine/DoctrineFixturesBundle/pull/324
