### ISSUE TITLE
[LoadDataFixturesDoctrineCommand] doctrine:fixtures:load  --env=test

### ISSUE THREAD

**Issue by liuggio** [doctrine/DoctrineFixturesBundle#34]
Hi,

Usually when we develop we have more than one set of fixtures,
for example, the fixtures are many more on stage than on test
So we created two folder foreach bundle  

DataFixtures / test / ORM / ... 
DataFixtures / ORM / ...       // stage

It would be nice if you could load a set of fixtures
depending from wich environment you select, for example for the 'dev' env. 
would be loaded the fixtures in bundleName / DataFixtures / dev / ORM / ...

The solution is easy just add a parameter and add a row on the row number 90.

I could do it, what do you think?

**Comment by lavoiesl** [comment]
Closing since test databases are already possible and issues already exists for selective loading: https://github.com/doctrine/data-fixtures/issues/169, https://github.com/doctrine/data-fixtures/issues/140
