### ISSUE TITLE
Add a description to this repository?

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineFixturesBundle#346]
This repository doesn't show any description at the moment:

![image](https://user-images.githubusercontent.com/73419/111170735-8d7f6800-85a4-11eb-91ed-dcd3e3399999.png)

symfony.com will soon use that description (obtained via GitHub API) in the bundles section, so it'd be nice to have a non-empty description. Thanks!

**Comment by greg0ire** [comment]
Good point, fixed, thanks!
