### ISSUE TITLE
Put fixtures outside of src code

### ISSUE THREAD

**Issue by eerison** [doctrine/DoctrineFixturesBundle#372]
I just want to raise up this issue #186 again to know the reason to have the fixtures inside of `src` code

the first argument that I saw is: it  wasn't used for test only!

but in the other hand we do not use this in production code, then composer map those classes that are not useful for production environment.

**Comment by greg0ire** [comment]
The history looks lost: 073990e1778083280075d613dcca84f847c8fc1a

Not sure where the docs where versioned before this commit. Since there is no argument, please make another proposal, test it on a real project, then send a PR to fix this.

**Comment by eerison** [comment]
Ok, I'm closing this issue for now, I can try provide a PR later ;)
