### ISSUE TITLE
Why it is strict in 2.6.x?

### ISSUE THREAD

**Issue by eerison** [doctrine/DoctrineFixturesBundle#373]
I'm trying to use the latest versions of doctrine, But I faced this library strict in [2.6.x](https://github.com/doctrine/DoctrineFixturesBundle/blob/3.4.x/composer.json#L26), any reason?

**Comment by stof** [comment]
This is not strict at `2.6.x`. `^2.6.0` means `>=2.6.0 <3.0.0`
