### ISSUE TITLE
Missing dependency Doctrine\Common when executing d:f:l command

### ISSUE THREAD

**Issue by AlvanOclock** [doctrine/DoctrineFixturesBundle#422]
After installing symfony `6.4.*` or `7.0.*` with `symfony new my_project_directory --version="6.4.*" --webapp` and installing the fixtures bundle, I have an error when i execute `php bin/console d:f:l` : 

> In BroadcastListener.php line 138:
> 
>   Attempted to load class "ClassUtils" from namespace "Doctrine\Common\Util".
>   Did you forget a "use" statement for another namespace?

It seems that there is a missing dependency `Doctrine\Common`. If i install it manually with `composer require doctrine/common`, it works properly.

How to replicate : 
- Install a fresh Symfony app (it's currently in `6.4.3`)
- Create an simple entity with `make:entity` and two simple string fields
- Create a migration
- Migrate the migration
- Install the fixtures bundle with `composer require --dev orm-fixtures`
- Create one simple fixture to add one entity with two fields in database.
- Execute the `doctrine:fixtures:load` command

Don't know if it's an issue with this bundle or the newest symfony version `6.4.3`. 
Also, i tried installing a fresh symfony project with `6.4.2` and I don't have the issue.

**Comment by fabpot** [comment]
This one can be closed as the issue comes from https://github.com/symfony/ux which implicitly depends on `doctrine/common`.

**Comment by fabpot** [comment]
See https://github.com/symfony/ux/issues/1469
