### ISSUE TITLE
Accessing Services from the Fixtures issue

### ISSUE THREAD

**Issue by palamar1982** [doctrine/DoctrineFixturesBundle#423]
Precondition:
Symfony version: 6.3.8
doctrine-fixtures-bundle version: 3.5.1

Issue
when I try to add a service by dependency injection 
![2024-02-27_12-34](https://github.com/doctrine/DoctrineFixturesBundle/assets/17453584/e0ab3c36-efeb-4c63-b8c1-8453916a0b96)

I am getting an error like this `Too few arguments to function Project\Tests\DataFixtures\AppFixtures::__construct(), 0 passed in /www/var/cache/dev/ContainerXXVW009/NotificationCenter_KernelDevDebugContainer.php on line 7231 and exactly 1 expected`

**Comment by derrabus** [comment]
Please use either https://github.com/symfony/symfony/discussions/ or https://github.com/doctrine/orm/discussions/ for support questions.

**Comment by Huluti** [comment]
I have the same issue while this behaviour is described there: https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html#accessing-services-from-the-fixtures

```php
public function __construct(
        private readonly ParameterBagInterface $params,
    ) {

    }
```

ArgumentCountError: Too few arguments to function App\DataFixtures\SubscriptionFixtures::__construct(), 0 passed in /var/www/html/vendor/doctrine/data-fixtures/src/Loader.php on line 228 and exactly 1 expected

**Comment by derrabus** [comment]
And my answer also applies to you.
