### ISSUE TITLE
Support doctrine/data-fixtures v2

### ISSUE THREAD

**Issue by bobvandevijver** [doctrine/DoctrineFixturesBundle#456]
### Feature Request

Add support for `doctrine/data-fixtures` v2: https://github.com/doctrine/data-fixtures/releases/tag/2.0.0

Maybe this can best be included with the v4 of this bundle?

**Comment by greg0ire** [comment]
I'm aware of this, and working on it, see the few last PRs I sent. Support will be added in the next minor, and support for v1 dropped in the next major. I plan to do that myself, but feel free to beat me to it.
