### ISSUE TITLE
doctrine:fixtures:load --purge-with-truncate fails

### ISSUE THREAD

**Issue by fkrauthan** [doctrine/DoctrineFixturesBundle#50]
If I run `app/console doctrine:fixtures:load --purge-with-truncate` I get the error `SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint`

**Comment by afilina** [comment]
Can we please add something like --ignore-foreign-keys so that I don't have to edit the core?

**Comment by deeky666** [comment]
@afilina "ignoring" foreign keys is a MySQL specific option which is not in that way available for other database vendors. Adding a MySQL specific option to data fixtures is not a good solution and won't happen.
Currently working on a solution in DBAL that uses some kind of abstraction to solve the problem for all platforms. Stay tuned.

**Comment by lukaszwit** [comment]
Fall into same issue today. Simply wasted time to resolve this manually. Mentioned "ignoring" flag could be abstraction for other rdbms and native for mysql.

**Comment by lavoiesl** [comment]
See doctrine/data-fixtures#127

**Comment by rudak** [comment]
'Hi guys' ^^ is there anything new ? ty

**Comment by edrush** [comment]
Hi, as rudak same question-thank you!

**Comment by deeky666** [comment]
This still is an issue that is not easy to solve across vendors. At least with the current development stage of DBAL. I had been working on something but haven't gotton to finish it. So "no" there is nothing new yet.

**Comment by NathanVss** [comment]
You can actually execute this command : 

> php app/console doctrine:schema:drop --force

**Comment by CyrilCharlier** [comment]
Same problem, i run a 
`$ php bin/console doctrine:database:drop --force
$ php bin/console doctrine:database:create
$ php bin/console doctrine:schema:update --force`

to solve (if it is a solution)...

**Comment by carlowens** [comment]
This seems to be doing the job for me as a runtests.sh script:

    php bin/console doctrine:database:drop --force --env=test
    php bin/console doctrine:database:create --env=test
    php bin/console doctrine:schema:update --force --env=test
    php bin/console doctrine:fixtures:load --env=test --no-interaction
    #test etc
    php bin/phpspec run
    php bin/behat

**Comment by kariolos** [comment]
I created a custom command for doing that , although updating schema every time it is a little bit frustrating.

Creating directory Command inside AppBundle 
```
<?php
namespace AppBundle\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;


class fixturesReloadCommand extends Command
{
    protected function configure()
    {
        $this
            // the name of the command (the part after "bin/console")
            ->setName('app:fixturesReload')

            // the short description shown while running "php bin/console list"
            ->setDescription('Drop/Create Database and load Fixtures ....')

            // the full command description shown when running the command with
            // the "--help" option
            ->setHelp('This command allows you to load dummy data by recreating database and loading fixtures...');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $application = $this->getApplication();
        $application->setAutoExit(false);

        $output->writeln([
            '===================================================',
            '*********        Dropping DataBase        *********',
            '===================================================',
            '',
        ]);

        $options = array('command' => 'doctrine:database:drop',"--force" => true);
        $application->run(new \Symfony\Component\Console\Input\ArrayInput($options));


        $output->writeln([
            '===================================================',
            '*********        Creating DataBase        *********',
            '===================================================',
            '',
        ]);

        $options = array('command' => 'doctrine:database:create',"--if-not-exists" => true);
        $application->run(new \Symfony\Component\Console\Input\ArrayInput($options));

        $output->writeln([
            '===================================================',
            '*********         Updating Schema         *********',
            '===================================================',
            '',
        ]);

        //Create de Schema
        $options = array('command' => 'doctrine:schema:update',"--force" => true);
        $application->run(new \Symfony\Component\Console\Input\ArrayInput($options));

        $output->writeln([
            '===================================================',
            '*********          Load Fixtures          *********',
            '===================================================',
            '',
        ]);

        //Loading Fixtures
        $options = array('command' => 'doctrine:fixtures:load',"--no-interaction" => true);
        $application->run(new \Symfony\Component\Console\Input\ArrayInput($options));

    }
}
```
And run the command from terminal

`php bin/console app:fixturesReload
`

**Comment by karser** [comment]
This seems to be shorter
```
bin/console doctrine:schema:drop --force \
&& bin/console doctrine:schema:update --force \
&& bin/console doctrine:fixtures:load -n
```
