### ISSUE TITLE
Add "--dump-sql" option to "doctrine:fixtures:load" command

### ISSUE THREAD

**Issue by MacDada** [doctrine/DoctrineFixturesBundle#60]
It would work the same as for example "doctrine:schema:create --dump-sql" and print sql instead of applying it to database.

**Comment by lavoiesl** [comment]
This would require a massive refactoring, possibly replacing the underlying connections by some dummy ones. It would also require to deal with corner cases around flushing/transactions. If this is really wanted, create an issue in https://github.com/doctrine/data-fixtures/ and will set the milestone to 2.0
