### ISSUE TITLE
[rfc] ability to serialize and dump reference repository.

### ISSUE THREAD

**Issue by makasim** [doctrine/DoctrineFixturesBundle#62]
It is pretty cool to have ability to get an entity in test by it is reference in fixtures. Current solution is to create  a command which is copy\past of data:load command and add there reference repository.

Now it is not possible because the reference repository is a local variable (So the only way to store it is copy\paste). I dont know how to do it best? any thoughts?

**Comment by PReimers** [comment]
@makasim is this still an issue?
