### ISSUE TITLE
add support for yml file fixtures with nelmio/alice

### ISSUE THREAD

**Issue by dbu** [doctrine/DoctrineFixturesBundle#64]
would be cool to support alice (and with it, faker) so that we can just load fixtures from simple files instead of writing code. see https://github.com/nelmio/alice

i can do a PR, but wanted to ask first
- should i extend doctrine:fixtures:load to support both? or do we rather do a new command, and what should that command be named?
- i propose to make alice an optional dependency and only load the service if alice is available.

right now i do a pseudo-fixture class that just uses alice.

```
use Nelmio\Alice\Fixtures;
class LoadPersonData implements FixtureInterface
{

    public function load(ObjectManager $manager)
    {
        Fixtures::load(__DIR__.'/data/person.yml', $manager);
        $manager->flush();
    }
}
```

**Comment by theofidry** [comment]
Purpose of [hautelook/AliceBundle](https://github.com/hautelook/AliceBundle).

**Comment by dbu** [comment]
oh, very cool! i created https://github.com/hautelook/AliceBundle/issues/72

can you do a pull request on the symfony-docs page http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html to explain that for generated data, faker/alice + AliceBundle is a thing to look at?

**Comment by theofidry** [comment]
That would be cool but it's not the docs of `symfony-docs` but of the bundle `DoctrineFixturesBundle` instead so not sure it's doable.

**Comment by dbu** [comment]
ah yes, that PR would need to go against this repository instead: https://github.com/doctrine/DoctrineFixturesBundle/blob/master/Resources/doc/index.rst

**Comment by alcaeus** [comment]
Closing here: this bundle is an integration for the Doctrine data-fixtures library. If you want to load alice fixtures there are better integrations out there.
