### ISSUE TITLE
orderedfixtures being skipped

### ISSUE THREAD

**Issue by ner0tic** [doctrine/DoctrineFixturesBundle#65]
I have  an ordered set of fixtures and am getting missing index errors but unless I'm reading the ouptut wrong it seems like its skipping the fixture that loads the missing index.
```bash
$ php app/console doctrine:fixtures:load 
Careful, database will be purged. Do you want to continue Y/N ?y
  > purging database
  > loading [1] Scss\UserBundle\DataFixtures\ORM\LoadUserData
  > loading [3] Scss\GeographyBundle\DataFixtures\ORM\LoadRegionData


                                                                                                                                                                                        
  [ErrorException]                                                                                                                                                                      
  Notice: Undefined index: ptc-bsa
```
[LoadUserData](http://pastebin.com/xqXSkngT) is ordered as 1, 
[LoadOrganizationData] (http://pastebin.com/qDXP1DYQ) is ordered as 2 
and [LoadRegionData] (http://pastebin.com/7V4U4h7q) is set for 3
 the index ptc-bsa is the only fixture within the LoadOrganizationData file to be loaded.

is this a bug or am i missing something?

**Comment by lavoiesl** [comment]
Your `LoadOrganizationData` is abstract and will not be loaded.
