### ISSUE TITLE
composer installation 

### ISSUE THREAD

**Issue by lskowronski** [doctrine/DoctrineFixturesBundle#85]
Hi,

when we will add only :

"doctrine/doctrine-fixtures-bundle": "dev-master"

compose will return error like:

 Problem 1
    - Installation request for doctrine/doctrine-fixtures-bundle dev-master -> satisfiable by doctrine/doctrine-fixtures-bundle[dev-master].
    - doctrine/doctrine-fixtures-bundle dev-master requires doctrine/data-fixtures * -> no matching package found.

So, when I added line: 

"doctrine/data-fixtures": "dev-master",

before doctrine-fixtures-bundle everything passed without any problems.

I think You should fix documentation because this can help others people.

Regards,
Łukasz

**Comment by lavoiesl** [comment]
doctrine/data-fixtures had a dot release since.
