### ISSUE TITLE
Actual namespace seems to not be working

### ISSUE THREAD

**Issue by AarSoftware** [doctrine/DoctrineFixturesBundle#90]
Hiho all!

I've just updated to Symfony2.3 stable. Following the official composer.json structure I changed this:

"minimum-stability": "dev",

to this:

"minimum-stability": "stable",

And the line "doctrine/doctrine-fixtures-bundle": "dev-master", couldn't be loaded, so I changed to "doctrine/doctrine-fixtures-bundle": "1.0.*@dev",

It's loading, but when clearing cache this savage message appears:

Fatal error: Class 'Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle' not found in blablabla/AppKernel.php on line 22

Dunno why it isn't being recognized now... As far as I now there isn't ANOTHER namespace change, is it?

Greetings!

**Comment by lavoiesl** [comment]
Is this still a problem as of today?

**Comment by fabpot** [comment]
Closing this old issue.
